[package]
name = "realtime-gateway"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
runtime-composition = { path = "../../crates/runtime-composition" }
tokio.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true

