/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ShopsSlugRouteImport } from './routes/shops.$slug'
import { Route as PickupPickupTokenRouteImport } from './routes/pickup.$pickupToken'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as AppUsageRouteImport } from './routes/app.usage'
import { Route as AppSnapshotsRouteImport } from './routes/app.snapshots'
import { Route as AppRoutesRouteImport } from './routes/app.routes'
import { Route as AppReceiptsRouteImport } from './routes/app.receipts'
import { Route as AppProvidersRouteImport } from './routes/app.providers'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppMerchantRouteImport } from './routes/app.merchant'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppApiKeysRouteImport } from './routes/app.api-keys'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AppRouteDiagnosticsRoutePolicyIdRouteImport } from './routes/app.route-diagnostics.$routePolicyId'
import { Route as AdminTenantsTenantIdRouteImport } from './routes/admin.tenants.$tenantId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/shops/$slug',
  path: '/shops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupPickupTokenRoute = PickupPickupTokenRouteImport.update({
  id: '/pickup/$pickupToken',
  path: '/pickup/$pickupToken',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppSnapshotsRoute = AppSnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantRoute = AppMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AppRouteDiagnosticsRoutePolicyIdRoute =
  AppRouteDiagnosticsRoutePolicyIdRouteImport.update({
    id: '/route-diagnostics/$routePolicyId',
    path: '/route-diagnostics/$routePolicyId',
    getParentRoute: () => AppRoute,
  } as any)
const AdminTenantsTenantIdRoute = AdminTenantsTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => AdminTenantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/billing': typeof AppBillingRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/routes': typeof AppRoutesRoute
  '/app/snapshots': typeof AppSnapshotsRoute
  '/app/usage': typeof AppUsageRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/pickup/$pickupToken': typeof PickupPickupTokenRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/app/route-diagnostics/$routePolicyId': typeof AppRouteDiagnosticsRoutePolicyIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/billing': typeof AppBillingRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/routes': typeof AppRoutesRoute
  '/app/snapshots': typeof AppSnapshotsRoute
  '/app/usage': typeof AppUsageRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/pickup/$pickupToken': typeof PickupPickupTokenRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/app/route-diagnostics/$routePolicyId': typeof AppRouteDiagnosticsRoutePolicyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/billing': typeof AppBillingRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/routes': typeof AppRoutesRoute
  '/app/snapshots': typeof AppSnapshotsRoute
  '/app/usage': typeof AppUsageRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/pickup/$pickupToken': typeof PickupPickupTokenRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/app/route-diagnostics/$routePolicyId': typeof AppRouteDiagnosticsRoutePolicyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/tenants'
    | '/app/api-keys'
    | '/app/billing'
    | '/app/merchant'
    | '/app/overview'
    | '/app/providers'
    | '/app/receipts'
    | '/app/routes'
    | '/app/snapshots'
    | '/app/usage'
    | '/checkout/$orderId'
    | '/login/callback'
    | '/pickup/$pickupToken'
    | '/shops/$slug'
    | '/admin/tenants/$tenantId'
    | '/app/route-diagnostics/$routePolicyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/tenants'
    | '/app/api-keys'
    | '/app/billing'
    | '/app/merchant'
    | '/app/overview'
    | '/app/providers'
    | '/app/receipts'
    | '/app/routes'
    | '/app/snapshots'
    | '/app/usage'
    | '/checkout/$orderId'
    | '/login/callback'
    | '/pickup/$pickupToken'
    | '/shops/$slug'
    | '/admin/tenants/$tenantId'
    | '/app/route-diagnostics/$routePolicyId'
  id:
    | '__root__'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/tenants'
    | '/app/api-keys'
    | '/app/billing'
    | '/app/merchant'
    | '/app/overview'
    | '/app/providers'
    | '/app/receipts'
    | '/app/routes'
    | '/app/snapshots'
    | '/app/usage'
    | '/checkout/$orderId'
    | '/login/callback'
    | '/pickup/$pickupToken'
    | '/shops/$slug'
    | '/admin/tenants/$tenantId'
    | '/app/route-diagnostics/$routePolicyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  PickupPickupTokenRoute: typeof PickupPickupTokenRoute
  ShopsSlugRoute: typeof ShopsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/shops/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/$pickupToken': {
      id: '/pickup/$pickupToken'
      path: '/pickup/$pickupToken'
      fullPath: '/pickup/$pickupToken'
      preLoaderRoute: typeof PickupPickupTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/snapshots': {
      id: '/app/snapshots'
      path: '/snapshots'
      fullPath: '/app/snapshots'
      preLoaderRoute: typeof AppSnapshotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/routes': {
      id: '/app/routes'
      path: '/routes'
      fullPath: '/app/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts': {
      id: '/app/receipts'
      path: '/receipts'
      fullPath: '/app/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/providers': {
      id: '/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/merchant': {
      id: '/app/merchant'
      path: '/merchant'
      fullPath: '/app/merchant'
      preLoaderRoute: typeof AppMerchantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/route-diagnostics/$routePolicyId': {
      id: '/app/route-diagnostics/$routePolicyId'
      path: '/route-diagnostics/$routePolicyId'
      fullPath: '/app/route-diagnostics/$routePolicyId'
      preLoaderRoute: typeof AppRouteDiagnosticsRoutePolicyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tenants/$tenantId': {
      id: '/admin/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AdminTenantsTenantIdRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
  }
}

interface AdminTenantsRouteChildren {
  AdminTenantsTenantIdRoute: typeof AdminTenantsTenantIdRoute
}

const AdminTenantsRouteChildren: AdminTenantsRouteChildren = {
  AdminTenantsTenantIdRoute: AdminTenantsTenantIdRoute,
}

const AdminTenantsRouteWithChildren = AdminTenantsRoute._addFileChildren(
  AdminTenantsRouteChildren,
)

interface AdminRouteChildren {
  AdminTenantsRoute: typeof AdminTenantsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTenantsRoute: AdminTenantsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppBillingRoute: typeof AppBillingRoute
  AppMerchantRoute: typeof AppMerchantRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppRoutesRoute: typeof AppRoutesRoute
  AppSnapshotsRoute: typeof AppSnapshotsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppRouteDiagnosticsRoutePolicyIdRoute: typeof AppRouteDiagnosticsRoutePolicyIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppBillingRoute: AppBillingRoute,
  AppMerchantRoute: AppMerchantRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppRoutesRoute: AppRoutesRoute,
  AppSnapshotsRoute: AppSnapshotsRoute,
  AppUsageRoute: AppUsageRoute,
  AppRouteDiagnosticsRoutePolicyIdRoute: AppRouteDiagnosticsRoutePolicyIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  PickupPickupTokenRoute: PickupPickupTokenRoute,
  ShopsSlugRoute: ShopsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
