[package]
name = "audit-worker"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
runtime-composition = { path = "../../crates/runtime-composition" }
serde_json = { workspace = true }
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
