[package]
name = "runtime-composition"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
async-nats = { version = "0.38.0" }
futures = { version = "0.3.31" }
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true

[lints]
workspace = true
